// lib/search-mock-data.ts
import type { CompanyArticle } from '@/services/company-articles';

export interface SearchArticle extends CompanyArticle {
  companyName: string;
  companyLogo: string | null;
  sector: string;
}

export const mockArticles: SearchArticle[] = [
  {
    id: 107301,
    headline: 'GlobalTrade Partners Announces $500M Strategic Alliance with Pacific Rim Consortium',
    description: 'The partnership will expand cross-border trade infrastructure across 14 Asia-Pacific markets starting Q3 2026.',
    dateTime: 'Mon, 18 May 2026 09:00:00 +0800',
    thumbImage: null,
    companyName: 'GlobalTrade Partners',
    companyLogo: null,
    sector: 'Business',
  },
  {
    id: 107302,
    headline: 'TeleReach Media Group Launches Next-Generation 5G Content Distribution Platform',
    description: 'The platform delivers ultra-low latency streaming and broadcast-quality video to over 200 million subscribers across Asia.',
    dateTime: 'Tue, 19 May 2026 10:30:00 +0800',
    thumbImage: null,
    companyName: 'TeleReach Media Group',
    companyLogo: null,
    sector: 'Communications',
  },
  {
    id: 107303,
    headline: 'BlockVault Exchange Completes $120M Series B Funding for DeFi Infrastructure Expansion',
    description: 'The round was led by Asia Digital Ventures and will fund institutional-grade custody services and on-chain settlement rails.',
    dateTime: 'Wed, 20 May 2026 08:00:00 +0800',
    thumbImage: null,
    companyName: 'BlockVault Exchange',
    companyLogo: null,
    sector: 'Cryptocurrency',
  },
  {
    id: 107304,
    headline: 'AsiaCapital Holdings Reports Record Q1 Revenue of $2.3B Amid Regional Market Recovery',
    description: 'Strong performance across equities and private credit divisions drove a 34% year-on-year increase in net income.',
    dateTime: 'Thu, 21 May 2026 07:00:00 +0800',
    thumbImage: null,
    companyName: 'AsiaCapital Holdings',
    companyLogo: null,
    sector: 'Finance',
  },
  {
    id: 107305,
    headline: 'MedTech Innovations Receives FDA Clearance for AI-Powered Diagnostic Imaging System',
    description: 'The system uses deep learning to detect early-stage pulmonary conditions with 97.4% sensitivity across diverse patient populations.',
    dateTime: 'Fri, 22 May 2026 11:00:00 +0800',
    thumbImage: null,
    companyName: 'MedTech Innovations',
    companyLogo: null,
    sector: 'Healthcare',
  },
  {
    id: 107306,
    headline: 'PrecisionManufacturing Corp Unveils Carbon-Neutral Production Facility in Singapore',
    description: 'The 420,000 sq ft facility uses 100% renewable energy and AI-driven process optimisation to reduce waste by 60%.',
    dateTime: 'Mon, 25 May 2026 09:30:00 +0800',
    thumbImage: null,
    companyName: 'PrecisionManufacturing Corp',
    companyLogo: null,
    sector: 'Industry',
  },
  {
    id: 107307,
    headline: 'LuxeTravel Asia Introduces Exclusive Members-Only Resort Collection Across Southeast Asia',
    description: 'The curated portfolio of 22 ultra-premium properties offers bespoke experiences from Bali to the Maldives for verified high-net-worth travellers.',
    dateTime: 'Tue, 26 May 2026 10:00:00 +0800',
    thumbImage: null,
    companyName: 'LuxeTravel Asia',
    companyLogo: null,
    sector: 'Lifestyle',
  },
  {
    id: 107308,
    headline: 'CloudSynth Technologies Launches Enterprise AI Platform for Automated Workflow Management',
    description: 'The platform integrates with over 300 enterprise tools and reduces operational overhead by an average of 42% for Fortune 500 clients.',
    dateTime: 'Wed, 27 May 2026 08:30:00 +0800',
    thumbImage: null,
    companyName: 'CloudSynth Technologies',
    companyLogo: null,
    sector: 'Technology',
  },
  {
    id: 107309,
    headline: 'NexusGroup Asia Completes $780M Acquisition of Regional Logistics and Cold Chain Network',
    description: 'The acquisition adds 38 distribution hubs across Malaysia, Thailand, and Vietnam, strengthening last-mile delivery capacity.',
    dateTime: 'Thu, 28 May 2026 07:30:00 +0800',
    thumbImage: null,
    companyName: 'NexusGroup Asia',
    companyLogo: null,
    sector: 'Business',
  },
  {
    id: 107310,
    headline: 'CryptoSecure Labs Launches Institutional-Grade Hardware Security Module for Digital Assets',
    description: 'The HSM supports multi-party computation and threshold signatures, enabling compliant custody for regulated asset managers.',
    dateTime: 'Fri, 29 May 2026 09:00:00 +0800',
    thumbImage: null,
    companyName: 'CryptoSecure Labs',
    companyLogo: null,
    sector: 'Cryptocurrency',
  },
  {
    id: 107311,
    headline: 'SingaporeFin Partners Unveils Sustainable Investment Framework for ESG Portfolio Construction',
    description: 'The framework applies proprietary carbon-adjusted return metrics across equities, green bonds, and impact private equity.',
    dateTime: 'Mon, 01 Jun 2026 08:00:00 +0800',
    thumbImage: null,
    companyName: 'SingaporeFin Partners',
    companyLogo: null,
    sector: 'Finance',
  },
  {
    id: 107312,
    headline: 'BioGenesis Research Announces Breakthrough in mRNA Vaccine Technology for Tropical Diseases',
    description: 'Clinical trials show 91% efficacy against dengue fever variants, with a low-cost formulation designed for equatorial distribution.',
    dateTime: 'Tue, 02 Jun 2026 10:00:00 +0800',
    thumbImage: null,
    companyName: 'BioGenesis Research',
    companyLogo: null,
    sector: 'Healthcare',
  },
  {
    id: 107313,
    headline: 'DataStream AI Releases Open-Source Large Language Model Optimised for Asian Languages',
    description: 'The 70B parameter model outperforms leading benchmarks on Mandarin, Japanese, Korean, and Bahasa Indonesia reasoning tasks.',
    dateTime: 'Wed, 03 Jun 2026 09:00:00 +0800',
    thumbImage: null,
    companyName: 'DataStream AI',
    companyLogo: null,
    sector: 'Technology',
  },
  {
    id: 107314,
    headline: 'MediaBridge Corp Expands Digital Advertising Network Across 12 Asia-Pacific Markets',
    description: 'The expansion adds programmatic inventory across 4,800 premium publisher sites, reaching an estimated 650 million monthly users.',
    dateTime: 'Thu, 04 Jun 2026 08:30:00 +0800',
    thumbImage: null,
    companyName: 'MediaBridge Corp',
    companyLogo: null,
    sector: 'Communications',
  },
  {
    id: 107315,
    headline: 'GreenEnergy Solutions Commissions 500MW Solar Farm in Borneo Industrial Park',
    description: 'The installation is the largest single-site solar project in Southeast Asia and will supply clean power to 180 manufacturing tenants.',
    dateTime: 'Fri, 05 Jun 2026 07:00:00 +0800',
    thumbImage: null,
    companyName: 'GreenEnergy Solutions',
    companyLogo: null,
    sector: 'Industry',
  },
];
